### ISSUE TITLE
New to RS3 ahk

### ISSUE THREAD

**Issue by dnguyen224** [kyroh/rotations_model_rs3#1]
Hello, I was looking for pvm macros and I was wondering what this script does?

**Comment by MildPanda** [comment]
Nothing, this isn't ahk. To me this looks like a config file. You couldn't do anything with it without adding more code or additional code that calls on this file.

**Comment by kyroh** [comment]
This is in fact the start of a config file. I had an idea for a script that takes inputs from a user I.e what gear they’re using and what boss they’re doing and then outputs the most optimal rotation. Never ended up doing any more work on it than writing what’s here and writing up the math on a whiteboard in my apartment.
